# Generated by Django 4.2 on 2024-12-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CribDashApp', '0005_apartment_delete_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='slug',
        ),
    ]
