# Generated by Django 4.2 on 2024-12-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CribDashApp', '0006_remove_apartment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
