# Generated by Django 4.2 on 2024-12-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CribDashApp', '0008_userprofile_remove_apartment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='apartments/')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(upload_to='apartment_images/'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
