# Generated by Django 4.2 on 2024-12-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CribDashApp', '0009_apartments_apartment_created_at_userprofile_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apartments',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(upload_to='apartments/'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
