# Generated by Django 4.2 on 2024-12-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CribDashApp', '0011_apartments_apartment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartments',
            new_name='Apartmentz',
        ),
    ]
