# Generated by Django 4.2 on 2024-12-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CribDashApp', '0012_rename_apartments_apartmentz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartmentz',
            new_name='Apartments',
        ),
    ]
