# Generated by Django 4.2 on 2024-12-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CribDashApp', '0015_appartment_apartment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment',
            new_name='Apartments',
        ),
    ]
