# Generated by Django 4.2 on 2024-12-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CribDashApp', '0016_rename_apartment_apartments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='created_at',
        ),
    ]
