# Generated by Django 4.2 on 2024-12-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CribDashApp', '0017_remove_apartments_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinquiry',
            name='date_submitted',
        ),
    ]
