# Generated by Django 4.2 on 2024-12-05 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CribDashApp', '0018_remove_contactinquiry_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
