# Generated by Django 4.2 on 2024-12-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CribDashApp', '0022_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appartment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
    ]
